import { useEffect, useState } from "react";
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [name, setName] = useState("no name");
  useEffect(() => {
    fetch('/api/chat')
      .then(res => res.json())
      .then(res => setName(res.name));
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          Name: {name}
        </div>
      </main>
    </>
  )
}
